### ISSUE TITLE
AUR package no longer working

### ISSUE THREAD

**Issue by basedtho** [buckket/twtxt#149]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 7.1.1 (/usr/lib/python3.8/site-packages), Requirement.parse('click<7,>=6.7'), {'twtxt'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/twtxt", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'click<7,>=6.7' distribution was not found and is required by twtxt
```

**Comment by KenwoodFox** [comment]
I've also got this issue too. 
Python-click is v 8 https://archlinux.org/packages/community/any/python-click/
can we fix this in the PKGBUILD or do we have to upgrade the version here?

**Comment by buckket** [comment]
Dependencies have been bumped, when I create another release I’ll also update the AUR PKGBUILD.

**Comment by buckket** [comment]
So twtxt is working again, sadly the AUR package is not, as there are problems with upstream dependencies: https://bugs.archlinux.org/task/76326. Will close this as soon as everything is in a working state.

Workaround is to install in a venv for now…
